version: "3.3"

services:
  #########
  # MySQL #
  #########
  mariadb:
    image: mariadb
    ports: 
      - "3306:3306"
    volumes: 
      - ./data/mariadb:/var/lib/mysql
      - ./mariadb/my.cnf:/etc/mysql/my.cnf
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"

  ###########
  # PHP-FPM #
  ###########
  phpfpm:
    build: 
      context: './php/'
    ports: 
      - "9000:9000"
      - "9003:9003"
    user: "${UID}:${GID}"  
    volumes:
      - "${WWW_ROOT}:/var/www/html:rw"
    networks:
      - backend
      - frontend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003 mode=debug  


  ###########
  # Traefik #
  ###########
  reverse-proxy:
    image: traefik
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=postmaster@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "${TRAEFIK_PORT_DASHBOARD}:8080"
    networks:
      - frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./letsencrypt:/letsencrypt"
      - "./configuration:/configuration/"  

  ##########
  # Apache #
  ##########   
  httpd:
    build:
      context: './httpd/'
    volumes:
      - "${WWW_ROOT}:/var/www/html"
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.httpd.rule=Host(`dev-docker.lan`) || Host(`portfolio.lan`) || Host(`projectmanager-docker.lan`)"
      - "traefik.http.routers.httpd.entrypoints=websecure"
      - "traefik.http.routers.httpd.tls.certresolver=myresolver"  

  ##############
  # phpMyAdmin #
  ##############
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    networks:
      - backend
      - frontend
    environment:
      - PMA_ARBITRARY=1    
      - PMA_HOST=mariadb
      - UPLOAD_LIMIT=128M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin-docker.lan`)"

networks:
  backend:        
  frontend:        
